(update) login process, request process
the-bedheads/goldilocks pull request #46
Opened 2020-11-05 19:38 UTC by mconner89

2020-11-05 19:59 UTC, jstrzesz commented on server/db/routes/requestRoutes.js
> +/* eslint-disable linebreak-style */
remove es-lint disable

2020-11-05 19:59 UTC, jstrzesz commented on server/db/routes/userRoutes.js
> +    console.log('here?');
remove

2020-11-05 20:00 UTC, jstrzesz commented on server/db/routes/userRoutes.js
> +        console.log(response, 'wheres my fucking response');
remove

2020-11-05 20:00 UTC, jstrzesz commented on server/routes/dashboard.js
> +  // console.log(req, 'body in post route from dashboard.js');
remove

2020-11-05 20:00 UTC, jstrzesz commented on server/routes/jwtAuth.js
> +    console.log('Entered variables', firstName, lastName, email, password);
remove console.logs

2020-11-05 20:01 UTC, jstrzesz commented on src/components/landing/auth/Login.tsx
> +          console.log(data, 'data from login.tsx line 40');
remove

2020-11-05 20:01 UTC, jstrzesz commented on src/components/landing/auth/Login.tsx
>        console.log(parseRes.jwtToken);
remove

2020-11-05 20:01 UTC, jstrzesz commented on src/components/landing/auth/Login.tsx
>          console.log('Logged in? ', isAuthenticated);
remove

2020-11-05 20:01 UTC, jstrzesz commented on src/components/landing/auth/Signup.tsx
>          console.log(parseRes.jwtToken);
remove

2020-11-05 20:02 UTC, jstrzesz requested changes
all console.logs must be removed. Also, remove vulgar language from code and commits.

2020-11-06 00:26 UTC, jessrichmond approved these changes

2020-11-06 00:27 UTC, gregthompson27 approved these changes

2020-11-06 00:27 UTC, merged