Render/reviews
the-bedheads/goldilocks pull request #80
Opened 2020-11-14 20:44 UTC by slatzz

2020-11-14 20:50 UTC, jstrzesz commented on server/db/routes/reviewRoutes.js
> +    console.info(reviews);
remove

2020-11-14 20:52 UTC, jstrzesz commented on src/components/landing/auth/Signup.tsx
> +            <br />
remove br tag, use css instead

2020-11-14 20:53 UTC, jstrzesz commented on src/components/landing/auth/UserDetailsForm.tsx
> +          <br />
see above comment

2020-11-14 20:53 UTC, jstrzesz commented on src/components/listing/HostReviews.tsx
> +                      <br />
see above comment

2020-11-14 20:54 UTC, jstrzesz commented on src/components/listing/UserReviews.tsx
> +            <br />
see above comment

2020-11-14 20:54 UTC, jstrzesz commented on src/components/listing/UserReviews.tsx
> +            <br />
see above comment

2020-11-14 20:54 UTC, jstrzesz requested changes
see comments

2020-11-14 21:16 UTC, mconner89 approved these changes

2020-11-15 00:06 UTC, jessrichmond approved these changes

2020-11-15 00:07 UTC, merged